name: Deploy to Firebase

on:
  push:
    branches:
      - main   # or whichever branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNTS }}" > ${HOME}/firebase-key.json
          firebase auth:login:ci || true
          firebase use --add kuraa-galaan-backend
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ HOME }}/firebase-key.json

      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --project kuraa-galaan-backend
