name: Deploy Firebase (Hosting + Functions)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Authenticate to Google Cloud
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud-key.json
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > "$GOOGLE_APPLICATION_CREDENTIALS"
          gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS" || true

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          GCLOUD_PROJECT: kuraa-galaan-prod
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcloud-key.json
        run: |
          firebase deploy --only hosting,functions --project "$GCLOUD_PROJECT"
